# Spring settings
spring.application.name=staff-manager
server.port=8080
spring.config.import=optional:file:.env[.properties]
spring.jackson.serialization.indent-output=true

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Docker
spring.docker.compose.enabled=false